apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-backend-deployment # this will be the deployment name
  labels:
    app: helloyoubackend
spec:
  replicas: 2 # number of pods to be created
  selector:
    matchLabels:
      app: helloyoubackend # have this matched with metadata.labels.app
  template:
    metadata:
      labels:
        app: helloyoubackend # have this matched with metadata.labels.app
    spec:
      containers:
        - name: myhello-project-backend
          image: kleydocker/myhello_project_backend:1.0
          ports:
            - containerPort: 8080
