apiVersion: v1
kind: Service
metadata:
  name: hello-backend-service
spec:
  type: NodePort
  selector:
    app: helloyoubackend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
